### ISSUE TITLE
プロキシサーバからhttps://cvepremium.circl.luへの接続が拒否され情報が取得できない

### ISSUE THREAD

**Issue by yyosioka** [KoukiHama/sw360#74]
### Description

プロキシサーバからhttps://cvepremium.circl.luへの接続が拒否され情報が取得できない
アクセス数が多くブラックリストに登録されてしまったのかhttps://cvepremium.circl.luへの接続が
拒否される現象が発生しています。回避方法をご教授ください。

web画面からもhttps://cvepremium.circl.luに接続することができません。

#### How to reproduce
1 git clone https://github.com/eclipse/sw360.git
2 cd sw360
3 git checkout -b sw360-16.0.0-M1 refs/tags/sw360-16.0.0-M1
4 docker build --cpu-period=100000 --cpu-quota=50000 -t sw360 .
4 docker-compose up

5 CVE-SEARCHを有効化
sw360 Dockerの中に入って以下のファイルを編集
/app/sw360/tomcat-9.0.33/webapps/schedule/WEB-INF/classes
sw360.properties

以下の値を編集しました
autostart = cvesearchService

6 　CVE-SEARCHの起動URLを変更
sw360 Dockerの中に入って以下のファイルを編集
/app/sw360/tomcat-9.0.33/webapps/cvesearch/WEB-INF/classes
cvesearch.properties

以下の値を編集しました
cvesearch.host=https://cvepremium.circl.lu

7 docker再起動で値反映
docker-compose down
docker-compose up

### Versions

sw360-16.0.0-M1

#### SW360 logs

2022-12-19 09:56:01 INFO  CveSearchHandler:133 - Starting CveSearch update...
2022-12-19 09:57:20 ERROR CveSearchGuesser:57 - Unable to tunnel through proxy. Proxy returns "HTTP/1.1 503 Service Unavailable"
java.io.IOException: Unable to tunnel through proxy. Proxy returns "HTTP/1.1 503 Service Unavailable"
        at sun.net.www.protocol.http.HttpURLConnection.doTunneling(HttpURLConnection.java:2177) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:199) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250) ~[?:?]
        at java.net.URL.openStream(URL.java:1165) ~[?:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchApiImpl.getParsedContentFor(CveSearchApiImpl.java:53) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchApiImpl.getParsedCveSearchMetadata(CveSearchApiImpl.java:77) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchApiImpl.allVendorNames(CveSearchApiImpl.java:118) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchGuesser.addVendorGuesserIfNeeded(CveSearchGuesser.java:55) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchGuesser.guessVendors(CveSearchGuesser.java:97) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchGuesser.guessVendorAndProducts(CveSearchGuesser.java:116) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchGuesser.guessVendorAndProducts(CveSearchGuesser.java:111) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.heuristics.SearchLevels.guessForRelease(SearchLevels.java:169) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.heuristics.SearchLevels.lambda$addGuessingSearchLevels$3(SearchLevels.java:148) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.heuristics.SearchLevels.lambda$apply$0(SearchLevels.java:98) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1632) ~[?:?]
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127) ~[?:?]
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543) ~[?:?]
        at org.eclipse.sw360.cvesearch.datasource.heuristics.Heuristic.run(Heuristic.java:68) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.datasource.CveSearchWrapper.searchForRelease(CveSearchWrapper.java:37) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at org.eclipse.sw360.cvesearch.service.CveSearchHandler.updateForRelease(CveSearchHandler.java:62) ~[src-cvesearch-15.1.0-SNAPSHOT.jar:?]
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) [?:?]
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) [?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) [?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) [?:?]
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) [?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) [?:?]
        at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:553) [?:?]

**Comment by KoukiHama** [comment]
ローカルにCVE-Serverに建てて、そこを情報取得先にすることで、CVE本家へのアクセスを減らすことができます。　
https://cve-search.github.io/cve-search/getting_started/installation.html

ローカルにインスタンスを構築した後は、以下のように設定するとOKです。

cvesearch.host=https://localhost:5000

@yyosioka

**Comment by yyosioka** [comment]
@KoukiHama  回答ありがとうございます。　CVE-SearchのDockerについても実績ありますでしょうか。https://cve-search.github.io/cve-search/docker/docker.html

**Comment by KoukiHama** [comment]
Docker構築のものを使ったという話は特に聞いたことがありません。ただ、ネットワーク設定次第では可能だと思います。

**Comment by yyosioka** [comment]
ありがとうございます。回答頂いたので本件は閉じます
